model:
  name: 'ownunet'
  alias: 'ownunet_mae'
  in_channels: 1
  classes: 1
  activation: 'sigmoid'
  dropout: 0.0
  pretrained_encoder_path: '/home/smadper/TFM/mae_encoder_best3.pth'

dataset:
  root: '/home/smadper/TFM/datasets/laticifers'
  image_size: [512, 512]
  patch_size: [512, 512]
  stride: [256, 256]
  num_patches: 20
  dataset_csv: 'laticifer_dataset_index.csv'
  num_workers: 8

train:
  batch_size: 8
  num_epochs: 100
  learning_rate: 0.0001
  accumulation_steps: 1
  save_dir: '/home/smadper/TFM/checkpoints'
  log_interval: 1
  patience: 20

test:
  batch_size: 1
  save_dir: '/home/smadper/TFM/results'
