model:
  name: 'manet'
  alias: 'manet_vgg16_bn'
  encoder_name: 'vgg16_bn'
  encoder_weights: None
  in_channels: 1
  classes: 1
  activation: 'sigmoid'
  dropout: 0.0

dataset:
  root: '/home/smadper/TFM/datasets/laticifers'
  image_size: [512, 512]
  dataset_csv: 'laticifer_dataset_index.csv'

train:
  batch_size: 4
  num_epochs: 150
  learning_rate: 0.001
  accumulation_steps: 1
  save_dir: '/home/smadper/TFM/checkpoints'
  log_interval: 1
  patience: 20

test:
  batch_size: 4
  save_dir: '/home/smadper/TFM/results'