model:
  name: 'ownunet'
  alias: 'ownunet'
  encoder_name: 'resnet18'
  encoder_weights: None
  in_channels: 1
  classes: 1
  activation: 'sigmoid'
  dropout: 0.0

dataset:
  root: '/data/smadper@alumno.upv.es/TFM/datasets/laticifers'
  image_size: [512, 512]
  patch_size: [512, 512]
  stride: [256, 256]
  num_patches: 20
  dataset_csv: 'laticifer_dataset_index.csv'
  num_workers: 8

train:
  batch_size: 8
  num_epochs: 150
  learning_rate: 0.0001
  accumulation_steps: 1
  save_dir: '/home/smadper/TFM/checkpoints'
  log_interval: 1
  patience: 15

test:
  batch_size: 1
  save_dir: '/home/smadper/TFM/results'