model:
  name: 'unet'
  alias: 'unet_resnet34'
  encoder_name: 'resnet34'
  encoder_weights: 'imagenet'
  in_channels: 1
  classes: 1
  activation: 'sigmoid'

dataset:
  root: '/home/smadper/TFM/datasets/laticifers'
  image_size: [512, 512]
  csv_name: 'laticifer_dataset_index.csv'

train:
  batch_size: 8
  num_epochs: 150
  learning_rate: 0.001
  accumulation_steps: 1
  save_dir: '/home/smadper/TFM/checkpoints'
  log_interval: 1
  patience: 15

test:
  batch_size: 8
  save_dir: '/home/smadper/TFM/results'
