model:
  name: 'unet'
  alias: 'unet_resnet18'
  encoder_name: 'resnet18'
  encoder_weights: None
  in_channels: 1
  classes: 1
  activation: 'sigmoid'
  dropout: 0.2

dataset:
  root: '/home/smadper/TFM/datasets/laticifers'
  image_size: [512, 512]
  csv_name: 'laticifer_dataset_index.csv'

train:
  batch_size: 4
  num_epochs: 150
  learning_rate: 0.001
  accumulation_steps: 1
  save_dir: '/home/smadper/TFM/checkpoints'
  log_interval: 1
  patience: 15

test:
  batch_size: 4
  save_dir: '/home/smadper/TFM/results'